languageCode = "en-us"
title = "Jill Bonovitz"
theme = "jill-artist-theme"

[build]
  writeStats = true

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"

# Site parameters
[params]
  defaultShowContentMap = false
  description = "Jill Bonovitz is an artist who makes sculptures with wire, vessels with clay and installations with both wire and clay. In wire she creates the edges of what is not there and in clay she creates the essence of what is."
  author = "Jill Bonovitz"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"

# Explicitly disable all taxonomies
[taxonomies]
  # Intentionally left empty - no taxonomies

# Server configuration to handle non-existent paths
[server]
  [[server.redirects]]
    from = "/categories/**"
    to = "/404.html"
    status = 404
    force = true
  
  [[server.redirects]]
    from = "/tags/**" 
    to = "/404.html"
    status = 404
    force = true